name: richtalk
description: Richtalk App.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 3.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  pull_to_refresh: ^2.0.0
  firebase_auth: ^1.1.0
  cloud_firestore: ^1.0.6
  firebase_storage: ^8.0.0
  firebase_core:
  firebase_messaging:
  country_code_picker: ^2.0.1
  image_cropper: ^1.3.1
  image_picker:
  cached_network_image: ^2.5.1
  get: ^3.24.0
  permission_handler:
  agora_rtc_engine: ^3.2.1
  firebase_dynamic_links: ^0.5.0+11
  flutter_local_notifications:
  share: ^0.6.5+4
  http: ^0.13.2
  loading_indicator:
  package_info_plus: ^1.0.2
  url_launcher: ^6.0.9
  dotted_border: ^2.0.0
  mailto: ^2.0.0
  contacts_service: ^0.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
# For information on the generic Dart part of this file, see the
# following page: https://dart.tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: RobotoMedium
      fonts:
        - asset: fonts/Roboto-Medium.ttf

    - family: RobotoRegular
      fonts:
        - asset: fonts/Roboto-Regular.ttf

    - family: RobotoBold
      fonts:
        - asset: fonts/Roboto-Bold.ttf

    - family: InterThin
      fonts:
        - asset: fonts/InterThin.ttf

    - family: InterExtraLight
      fonts:
        - asset: fonts/Inter-ExtraLight.ttf

    - family: InterLight
      fonts:
        - asset: fonts/Inter-Light.ttf

    - family: InterExtraBold
      fonts:
        - asset: fonts/Inter-ExtraBold.ttf

    - family: InterBold
      fonts:
        - asset: fonts/Inter-Bold.ttf

    - family: InterSemiBold
      fonts:
        - asset: fonts/Inter-SemiBold.ttf

    - family: InterRegular
      fonts:
        - asset: fonts/Inter-Regular.ttf

    - family: InterMedium
      fonts:
        - asset: fonts/Inter-Medium.ttf

    - family: RobotoLight
      fonts:
        - asset: fonts/Roboto-Light.ttf

    - family: RobotoRegular
      fonts:
        - asset: fonts/Roboto-Regular.ttf